### ISSUE TITLE
Error: Did not provide required argument apptitle!

### ISSUE THREAD

**Issue by keeth** [shovon/generator-react-material-ui#8]
other:ui keith $ yo react-material-ui
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Did not provide required argument apptitle!
    at null.<anonymous> (/usr/local/lib/node_modules/generator-react-material-ui/node_modules/yeoman-generator/lib/base.js:351:33)
    at Array.forEach (native)
    at Base.checkRequiredArgs (/usr/local/lib/node_modules/generator-react-material-ui/node_modules/yeoman-generator/lib/base.js:347:19)
    at argument (/usr/local/lib/node_modules/generator-react-material-ui/node_modules/yeoman-generator/lib/base.js:317:8)
    at new module.exports.generators.Base.extend.constructor (/usr/local/lib/node_modules/generator-react-material-ui/app/index.js:9:10)
    at Environment.instantiate (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:282:10)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:15)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:318:24)
    at /usr/local/lib/node_modules/yo/lib/cli.js:91:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)

other:ui keith $ yo --version
1.4.5
other:ui keith $ node --version
v0.12.0

it works when i do yo react-material-ui my-project-title

**Comment by lastjune** [comment]
i got the same error today. Did you get this issue fixed? @keeth

**Comment by secretgspot** [comment]
me too

**Comment by shovon** [comment]
@keeth, @lastjune, @secretgspot it was a documentation mistake on my part. Should be updated in 495e8522a1a6eded181d636b723a0fcc203e478c. Sorry about that.

So, when generating your app, be sure to add an `apptitle` parameter like so:

``` bash
yo react-material-ui my-app # or anything other than `my-app`
```
